version: '3.7'
services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/var/www/staticfiles  # 静的ファイルを保存するためのボリュームを追加
    expose:
      - 8000
    env_file:
      - ./.env

  nginx:
    build: ./nginx
    ports:
      - "8001:80"
    volumes:
      - static_volume:/var/www/staticfiles  # web コンテナと同じボリュームをマウント
    depends_on:
      - web

  http:
    image: steveltn/https-portal:1
    container_name: http-rakuten-scraping
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    ports:
      - "80:80"
      - "443:443"
    links:
      - web
    environment:
      DOMAINS: "rakuten-scraping.ars-system.net -> http://nginx:80/"
      STAGE: "local"

# ボリュームの定義
volumes:
  static_volume: